### ISSUE TITLE
Do not hardcode the path to cargo binaries

### ISSUE THREAD

**Issue by Netzeband** [codeitlikemiley/leptos-fmt#1]
Hello

At the moment the path to the cargo binary `leptosfmt` is hard coded by taking the user directory and then adding `.cargo/bin/leptosfmt` to it. However, this is can be the wrong path in some cases. When someone has set the `CARGO_HOME` environment variable the location is at `$CARGO_HOME/bin/leptosfmt`. In my case I did this, because my user directory contains a special character, which sometimes lead to issues when running binaries from the cargo directory.

**Comment by codeitlikemiley** [comment]
Thanks for the feedback , ill take a look into this matter, and possible create a new PR to fix this issue

**Comment by Netzeband** [comment]
Thank you very much.
