### ISSUE TITLE
Leptosfmt installation detection does not work cross platform

### ISSUE THREAD

**Issue by SlyCedix** [codeitlikemiley/leptos-fmt#5]
This line:
https://github.com/codeitlikemiley/leptos-fmt/blob/47415428a2bfcf4ab8ac90846abe70b6d544874f/src/extension.ts#L14

references the file path in a way that does not correctly resolve the file path on windows.

You may want to use a dependency like [lookpath](https://www.npmjs.com/package/lookpath) to resolve the location from the name alone. It may also be good to have a configuration option where one can provide a direct executable path in case Leptosfmt cannot be found normally.

**Comment by codeitlikemiley** [comment]
kindly check v0.0.6 i added custom path on settings for leptos 

https://github.com/codeitlikemiley/leptos-fmt/pull/8

**Comment by codeitlikemiley** [comment]
would like to know if this would fix the issue on windows , as i have
