### ISSUE TITLE
Use a descriptive extension namespace for configuration variables and commands

### ISSUE THREAD

**Issue by SlyCedix** [codeitlikemiley/leptos-fmt#6]
https://github.com/codeitlikemiley/leptos-fmt/blob/47415428a2bfcf4ab8ac90846abe70b6d544874f/package.json#L25C1-L25C52

https://github.com/codeitlikemiley/leptos-fmt/blob/47415428a2bfcf4ab8ac90846abe70b6d544874f/src/extension.ts#L22C1-L22C95

Instead of "extension.formatWithLeptosfmt" you may want to change these to "leptos-fmt.format" for example. So that the origin of the command is more descriptive.

**Comment by codeitlikemiley** [comment]
https://github.com/codeitlikemiley/leptos-fmt/pull/9 done
